{% set name = "dython" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc6c2a53ec0b01a9987bc00e617c7956fdaabcb0ca89af4ba8b32c1e159fc7ea

build:
  number: 0
  noarch: python
  script:
    - cp ${RECIPE_DIR}/VERSION .  # [not win]
    - cp ${RECIPE_DIR}/DESCRIPTION.md .  # [not win]
    - copy %RECIPE_DIR%\VERSION .  # [win]
    - copy %RECIPE_DIR%\DESCRIPTION.md .  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - pandas >=0.23.4
    - python >=3.6
    - scikit-learn
    - scikit-plot >=0.3.7
    - scipy
    - seaborn

test:
  imports:
    - dython
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://shakedzy.xyz/dython
  summary: A set of data tools in Python
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: http://shakedzy.xyz/dython/getting_started/installation/
  dev_url: http://shakedzy.xyz/dython/modules/data_utils/

extra:
  recipe-maintainers:
    - sarthakpati
